<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Servers</name>
   <tag></tag>
   <elementGuidId>934f8237-2553-4986-883d-84faf63accb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > a.flex.items-center > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-main']/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f286c40d-0f6c-45f0-9565-c141ffd639e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Servers</value>
      <webElementGuid>3522ad69-17fb-4501-9c33-3076cbb23aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-main&quot;)/ul[@class=&quot;nav navbar-nav main-menu&quot;]/li[@class=&quot;active&quot;]/a[@class=&quot;flex items-center&quot;]/span[1]</value>
      <webElementGuid>f628bf94-4b16-4fa2-abc9-25c3946186a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-main']/ul/li/a/span</value>
      <webElementGuid>eb52669e-832e-408a-80c6-468b9ed3c54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature Request'])[2]/following::span[1]</value>
      <webElementGuid>e8330c98-5f61-4213-bb16-f3c3c9a092c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[2]/following::span[1]</value>
      <webElementGuid>5693dd71-0067-40a7-8125-0926717cad81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Applications'])[1]/preceding::span[1]</value>
      <webElementGuid>c7c6230a-3fcd-4f4b-acde-4820cced877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atomic Deployment'])[1]/preceding::span[2]</value>
      <webElementGuid>e3f5c612-5f2b-4fa0-9a7f-c9d2cf94626e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Servers']/parent::*</value>
      <webElementGuid>f4bc89ee-5557-4d12-a01a-31ba36e58a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span</value>
      <webElementGuid>cd401091-a7ac-4549-b618-2f1102bd0a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Servers' or . = 'Servers')]</value>
      <webElementGuid>89b37879-4040-4925-a0f9-958b11d4aaf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
