<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Backups</name>
   <tag></tag>
   <elementGuidId>c92c326c-5d76-4d53-9747-6cfcf39cfcbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a.flex.items-center > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-main']/ul/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a6c8e7e-5726-4752-a78f-d29411049a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backups</value>
      <webElementGuid>9c7fe6ef-0576-4f87-aced-0301135966bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-main&quot;)/ul[@class=&quot;nav navbar-nav main-menu&quot;]/li[4]/a[@class=&quot;flex items-center&quot;]/span[1]</value>
      <webElementGuid>62cbcc8b-b04f-46a6-b70a-49476599c119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-main']/ul/li[4]/a/span</value>
      <webElementGuid>93f88a00-8fe3-4a5d-8237-c4a17ce95e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atomic Deployment'])[1]/following::span[1]</value>
      <webElementGuid>0d30c143-9257-495a-b324-5d89af7ced11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Applications'])[1]/following::span[2]</value>
      <webElementGuid>67acadf6-d06a-4df5-9b2d-512d2e71d806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DNS Manager'])[1]/preceding::span[1]</value>
      <webElementGuid>e5128e71-5cf9-4676-9b7d-aaf68e432fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teams'])[1]/preceding::span[2]</value>
      <webElementGuid>6089e85d-7064-417e-b820-75440eb5ab55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Backups']/parent::*</value>
      <webElementGuid>2f27973a-cd47-4c15-94c4-c6a56bb8b368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>d5d600ad-3b2f-47fb-8278-c6e93f4f82e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Backups' or . = 'Backups')]</value>
      <webElementGuid>b47279ab-0ec2-4c11-8d0b-8f31567b2e8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
