<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateNewBackup</name>
   <tag></tag>
   <elementGuidId>a95d5925-0291-496d-b086-c8b00996e27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.whitespace-pre-wrap.break-word</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content-wrapper']/section/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>43c2a72e-3a83-4bac-a8d2-6072a3dfa161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-pre-wrap break-word</value>
      <webElementGuid>7f33a54f-20b8-43f4-9ded-3f36fb6359fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Backup</value>
      <webElementGuid>e9d28cbf-ce65-4265-be7e-4975be4c2381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/section[@class=&quot;mb-6 section-header&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;flex items-center space-x-4&quot;]/h1[@class=&quot;whitespace-pre-wrap break-word&quot;]</value>
      <webElementGuid>a9a996e3-97d3-4472-bd06-5aac24c24fa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-wrapper']/section/div/div/h1</value>
      <webElementGuid>ed149f95-4ba6-4713-be23-8aa9552211b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backups'])[2]/following::h1[1]</value>
      <webElementGuid>36fedaae-4d21-4d39-bc1e-e173127b45fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse Menu'])[1]/following::h1[1]</value>
      <webElementGuid>1530ce02-4c16-4251-8c5c-85e8fd790191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backup Instance'])[1]/preceding::h1[1]</value>
      <webElementGuid>04353cb0-7572-4e2b-b0cf-eae2111aa193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What do you plan to backup?'])[1]/preceding::h1[1]</value>
      <webElementGuid>00ccf1c0-a4e1-4c6e-b664-d263c2f4797d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create New Backup']/parent::*</value>
      <webElementGuid>b3e0a0db-86f9-45f3-b335-28efe33a5c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>5a8248a5-6f84-4568-b71f-370f65251b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Create New Backup' or . = 'Create New Backup')]</value>
      <webElementGuid>9fa78b69-41ad-4502-a475-22e077126104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
