<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BackupEmptyText-2</name>
   <tag></tag>
   <elementGuidId>5740ae19-c25d-44c4-b45c-13b1914ad519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-lg.mb-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content-wrapper']/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b00223de-5ab9-4e9b-bf02-b5d700d37c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-lg mb-7</value>
      <webElementGuid>c9af404e-41e0-4485-80e1-ab7c8887466f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configure your backups so you can easily restore your web applications and databases in the event of a server or web application issue.</value>
      <webElementGuid>a5613817-a985-44dc-82d3-46b86a9118e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;panel panel-default py-0 px-7&quot;]/div[@class=&quot;panel-body py-8 px-2 md:!px-8&quot;]/div[@class=&quot;md:flex md:items-center md:space-x-20 xl:space-x-32&quot;]/div[@class=&quot;md:w-2/4&quot;]/p[@class=&quot;text-lg mb-7&quot;]</value>
      <webElementGuid>930df345-00c5-4a7c-b43f-79225c58eac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-wrapper']/div/div/div/div/p</value>
      <webElementGuid>4e269e83-ad9c-426e-899e-9201c32d1ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect Your Web App &amp; Database Data with Backups'])[1]/following::p[1]</value>
      <webElementGuid>1ef758dd-7682-4f03-b60c-08f6512d44fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backups'])[2]/following::p[1]</value>
      <webElementGuid>466032d6-ac4f-41c2-8ee7-fc711d925167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Your First Backup'])[1]/preceding::p[1]</value>
      <webElementGuid>5c15979a-a4fe-4387-a8a1-cce5a6014cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Three Backup Storage Types'])[1]/preceding::p[1]</value>
      <webElementGuid>37bfd91d-ef62-4af6-bb15-97e19eae2970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Configure your backups so you can easily restore your web applications and databases in the event of a server or web application issue.']/parent::*</value>
      <webElementGuid>1716f8fa-3064-4bc3-8e5c-ddbf0552b12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/p</value>
      <webElementGuid>b330f7a7-a874-4d49-a3ff-30da15903e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Configure your backups so you can easily restore your web applications and databases in the event of a server or web application issue.' or . = 'Configure your backups so you can easily restore your web applications and databases in the event of a server or web application issue.')]</value>
      <webElementGuid>40c7f3fd-3af7-4bfb-84f0-b3937f730554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
