<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateFirstBackup</name>
   <tag></tag>
   <elementGuidId>1c57b3dc-67f4-42d0-8abf-5fe64b4b65e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.inline-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content-wrapper']/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d73a51d5-a2a9-4344-97f5-9a627a72304f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29993006-bb10-439b-a3a2-bd0725237c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://manage.runcloud.dev/backup/instances/create</value>
      <webElementGuid>333764e0-35b1-4a9a-b499-e573cb60ac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary inline-block</value>
      <webElementGuid>ccd88dae-8035-4445-9b6f-3d8ff57ab03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Your First Backup </value>
      <webElementGuid>4ec51b35-85dd-4915-8465-8421fbdc57e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;panel panel-default py-0 px-7&quot;]/div[@class=&quot;panel-body py-8 px-2 md:!px-8&quot;]/div[@class=&quot;md:flex md:items-center md:space-x-20 xl:space-x-32&quot;]/div[@class=&quot;md:w-2/4&quot;]/div[@class=&quot;flex space-x-2&quot;]/a[@class=&quot;btn btn-primary inline-block&quot;]</value>
      <webElementGuid>bac24065-944f-4633-ad1d-1f8647211d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-wrapper']/div/div/div/div/div/a</value>
      <webElementGuid>5021fdd3-0001-479b-982c-c476fe907eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Your First Backup')]</value>
      <webElementGuid>129b7119-a927-49fc-9d8c-b3c716c88fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect Your Web App &amp; Database Data with Backups'])[1]/following::a[1]</value>
      <webElementGuid>29275cad-2a24-4be7-903e-531491a8b102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backups'])[2]/following::a[1]</value>
      <webElementGuid>29a5b6ab-6f53-4909-8752-53a1be3a0ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Three Backup Storage Types'])[1]/preceding::a[1]</value>
      <webElementGuid>cf291298-edf3-4624-8da2-63f8f8f2c5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect Your Web Applications and Databases'])[1]/preceding::a[1]</value>
      <webElementGuid>4e7c8500-6ee0-481c-b553-2e48031a1798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Your First Backup']/parent::*</value>
      <webElementGuid>126d250d-07ab-4f68-a2db-6bd48c1d20d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://manage.runcloud.dev/backup/instances/create')]</value>
      <webElementGuid>9f1b64af-30ff-4960-9bad-0e1969a62a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/a</value>
      <webElementGuid>431afe33-887d-484e-89cf-991f712ed7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://manage.runcloud.dev/backup/instances/create' and (text() = 'Create Your First Backup ' or . = 'Create Your First Backup ')]</value>
      <webElementGuid>a02ec085-855b-4f02-ac93-efcdf1196c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
