<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Servers  Web Applications  Atomic Deplo_93d7b4</name>
   <tag></tag>
   <elementGuidId>150d9ccf-822a-4e1c-abf9-374a48c603a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebar-main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-main']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92f6a1b6-84ab-47aa-bc73-9a17f2f2b587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar-main</value>
      <webElementGuid>7b31cbce-15fc-4678-a218-f529b93c4651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-main overflow-auto transition-all duration-300</value>
      <webElementGuid>e2f6725d-0c67-4a34-a071-96ddfe3d19a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Servers  Web Applications  Atomic Deployment  Backups  DNS Manager  Teams   Settings  Billing  Collapse Menu</value>
      <webElementGuid>416c6213-bb01-4309-a6f1-7858989c3d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-main&quot;)</value>
      <webElementGuid>bb07b800-837d-4061-9659-12f63b1f510b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sidebar-main']</value>
      <webElementGuid>e5f0080f-e6fb-449d-ae88-7d4abbbd98cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/div</value>
      <webElementGuid>72981fef-29a6-45c9-821b-c2075fee1096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature Request'])[2]/following::div[3]</value>
      <webElementGuid>40689658-b534-40ef-ba6d-6c0da82fdab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[2]/following::div[3]</value>
      <webElementGuid>4ddc2da3-c2cc-4f65-849f-128c9dcde432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>032a2268-93f8-4f35-abd0-c717a3722ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sidebar-main' and (text() = '  Servers  Web Applications  Atomic Deployment  Backups  DNS Manager  Teams   Settings  Billing  Collapse Menu' or . = '  Servers  Web Applications  Atomic Deployment  Backups  DNS Manager  Teams   Settings  Billing  Collapse Menu')]</value>
      <webElementGuid>e36c45f1-2b07-41ba-9379-601b9f9c4e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
