<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropDownProfileImage</name>
   <tag></tag>
   <elementGuidId>2409ca86-9baf-41b4-a3b2-c514f6012fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-all']/div[2]/div[6]/a/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-full.shrink-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ddec3a0b-c4a6-4a24-98e8-e93cb4852721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.gravatar.com/avatar/acee74d7ee4008dc454dd4452b0138a1?s=80&amp;d=identicon&amp;r=g</value>
      <webElementGuid>cbadf5a9-8422-401d-a473-7fc2ecb9ed20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c4ee358c-fb16-4721-aafd-58da039b7027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-full shrink-0 </value>
      <webElementGuid>46bd394f-bf83-4af6-b90e-8b1862b2b29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-all&quot;)/div[@class=&quot;h-[62px] bg-blue-900 w-screen flex px-4 md:px-7 items-center text-white flex-wrap gap-2&quot;]/div[@class=&quot;relative dropdown&quot;]/a[1]/div[@class=&quot;image-holder relative left-0 top-0&quot;]/div[@class=&quot;w-9 h-9 border border-white/5 rounded-full&quot;]/div[@class=&quot;shrink-0&quot;]/img[@class=&quot;rounded-full shrink-0&quot;]</value>
      <webElementGuid>d545d6ce-44ee-4e24-b78f-060daf67dc0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-all']/div[2]/div[6]/a/div/div/div/img</value>
      <webElementGuid>e6d33e25-8bf7-4f17-ab52-e5560318da8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.gravatar.com/avatar/acee74d7ee4008dc454dd4452b0138a1?s=80&amp;d=identicon&amp;r=g')]</value>
      <webElementGuid>a9a777d2-36a5-4e23-b3ca-247e42b10133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>95cc62b3-afcd-4271-96ea-8c934ffcd0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.gravatar.com/avatar/acee74d7ee4008dc454dd4452b0138a1?s=80&amp;d=identicon&amp;r=g']</value>
      <webElementGuid>8161be74-bce0-4460-a444-7d1ea3e71231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
